### ISSUE TITLE
New Maint' Task "remove unused pictures"

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#1826] opened 2020-03-11 09:53 UTC
Idea from http://community.smartstore.com/index.php?/topic/50235-überflüssige-daten-aus-mediastorage-löschen/?p=279354

It would be great if such a task would be available centrally under the maintenance area in the backend at some point:

**"remove unused pictures**" or something

Does this come with **Media Manager** for version 4?

**Comment by muratcakir** [comment] 2020-03-12 02:54
Dupe of #333

**Closed by muratcakir** 2020-03-12 02:54 UTC
