### ISSUE TITLE
Form element overview in form configurator show wrong checks

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1889] opened 2020-05-08 10:20 UTC
The overview of Form Elements in a form-configurator form does not display the right checkmarks. for example: if you disable a form-element then all the other checkmarks from that element in the overview are also disabled (Is visible, Is mandatory) while they are ticked.

I Hope you understand, if not i will attach a picture.

**Comment by stefanmuellerdo** [comment] 2020-05-11 07:17
Hi Yorams, I assume you use the lastest version, that is Form Configurator 3.2.2.2 http://community.smartstore.com/index.php?/files/file/143-form-configurator/ -- 

Please attach **screenshots** indicating where the problem is, a) from the **configurator** showing the wron checks and b) form, as the shop customer sees the finally rendered form. Thank you!

**Comment by Yorams** [comment] 2020-05-11 07:33
Hi Stefan, I checked the version and it is 3.2.2.1. I will ask our integrator to update the plugin. Thanks.

**Comment by Yorams** [comment] 2020-05-11 08:08
I installed the latest version 3.2.2.2 but this does not resolve the problem.

As you can see, here is mandatory not checked.
![from-check2](https://user-images.githubusercontent.com/13483484/81538399-02738700-936f-11ea-8ff1-8dd0467f3e58.JPG)

But in the overview it is.
![from-check1](https://user-images.githubusercontent.com/13483484/81538374-f7205b80-936e-11ea-9558-ac15927b153c.JPG)

And if you make an element not active you see this:
![from-check3](https://user-images.githubusercontent.com/13483484/81538686-65fdb480-936f-11ea-8bce-e46821ee1c8c.JPG)

**Comment by Michael-Herzog** [comment] 2020-05-11 09:15
Hi,
this was fixed in the latest version (3.2.2.3) which was just uploaded to the marketplace.
Thanks for reporting.
Regards,
Michael Herzog

**Closed by Michael-Herzog** 2020-05-11 09:15 UTC
