### ISSUE TITLE
image attribute remove after some hours

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1849] opened 2020-04-06 12:34 UTC
![image](https://user-images.githubusercontent.com/31403448/78558926-b8a3f800-7828-11ea-98e1-a390bb28a89f.png)

**Comment by pineportal** [comment] 2020-04-06 13:25
in the new value IsTransient=true (incorrect)
in the Edite value IsTransient=false (correct)

**Comment by mgesing** [comment] 2020-04-06 13:39
I cannot reproduce that. MediaFile.IsTransient is set to false after the new value is saved. If you are using an older version, this may have been fixed by now.

**Closed by mgesing** 2020-04-06 13:39 UTC

**Comment by pineportal** [comment] 2020-04-06 13:41
i am user ver 3.2.2

**Comment by mgesing** [comment] 2020-04-06 14:50
Then it has probably been fixed in the meantime.
