### ISSUE TITLE
MegaMenu Brands and ContentSlider Images do not use the CDN specified for the store

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1783] opened 2020-01-03 16:03 UTC

**Comment by Michael-Herzog** [comment] 2020-07-28 13:18
Can't be reproduced. The code for CDN is central. If one picture can be loaded over CDN all pictures can. Please provide a link to a store where this problem occurs.

**Comment by muratcakir** [comment] 2020-08-03 17:30
The problem is the usage of the URL retrieving method. Details TBD.

**Comment by Michael-Herzog** [comment] 2020-10-16 16:55
Seems to be fixed now

**Closed by Michael-Herzog** 2020-10-16 16:55 UTC
Labels: bug
